package com.magicweight.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.magicweight.entity.ArticlesContents;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ARTICLES_CONTENTS".
*/
public class ArticlesContentsDao extends AbstractDao<ArticlesContents, Long> {

    public static final String TABLENAME = "ARTICLES_CONTENTS";

    /**
     * Properties of entity ArticlesContents.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property Url = new Property(1, String.class, "url", false, "URL");
        public final static Property Type = new Property(2, String.class, "type", false, "TYPE");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property Image = new Property(4, String.class, "image", false, "IMAGE");
        public final static Property IsSee = new Property(5, String.class, "isSee", false, "ISSEE");
        public final static Property IsDo = new Property(6, String.class, "isDo", false, "ISDO");
        public final static Property Delsign = new Property(7, String.class, "delsign", false, "DELSIGN");
    };


    public ArticlesContentsDao(DaoConfig config) {
        super(config);
    }
    
    public ArticlesContentsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ARTICLES_CONTENTS\" (" + //
                "\"id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"URL\" TEXT," + // 1: url
                "\"TYPE\" TEXT," + // 2: type
                "\"NAME\" TEXT," + // 3: name
                "\"IMAGE\" TEXT," + // 4: image
                "\"ISSEE\" TEXT," + // 5: isSee
                "\"ISDO\" TEXT," + // 6: isDo
                "\"DELSIGN\" TEXT);"); // 7: delsign
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ARTICLES_CONTENTS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ArticlesContents entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(2, url);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(3, type);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(5, image);
        }
 
        String isSee = entity.getIsSee();
        if (isSee != null) {
            stmt.bindString(6, isSee);
        }
 
        String isDo = entity.getIsDo();
        if (isDo != null) {
            stmt.bindString(7, isDo);
        }
 
        String delsign = entity.getDelsign();
        if (delsign != null) {
            stmt.bindString(8, delsign);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ArticlesContents readEntity(Cursor cursor, int offset) {
        ArticlesContents entity = new ArticlesContents( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // url
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // type
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // image
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // isSee
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // isDo
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // delsign
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ArticlesContents entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setImage(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIsSee(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIsDo(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setDelsign(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ArticlesContents entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ArticlesContents entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
