package com.magicweight.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ARTICLES_RECOMMEND".
 */
public class ArticlesRecommend {

    private Long id;
    private Integer no;
    private String name;
    private String image;
    private String delsign;

    public ArticlesRecommend() {
    }

    public ArticlesRecommend(Long id) {
        this.id = id;
    }

    public ArticlesRecommend(Long id, Integer no, String name, String image, String delsign) {
        this.id = id;
        this.no = no;
        this.name = name;
        this.image = image;
        this.delsign = delsign;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getNo() {
        return no;
    }

    public void setNo(Integer no) {
        this.no = no;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getDelsign() {
        return delsign;
    }

    public void setDelsign(String delsign) {
        this.delsign = delsign;
    }

}
